liongram/config/urls.py
import imp
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import index, url_view, url_parameter_view, function_view, ClassView, function_list_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/list/', function_list_view),
    path('fbv/', function_view),
    path('cbv/', ClassView.as_view(), name='cbv'),

    path('', index, name='index'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('posts/', include('posts.urls', namespace='posts')),

    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path

from .views import post_list_view, post_create_view, post_update_view, post_detail_view, post_delete_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    path('new/', post_create_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-update'),
    path('<int:id>/delete/', post_delete_view),
]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)


class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일')
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

liongram/posts/forms.py
from django import forms


class PostBaseForm(forms.Form):
    image = forms.ImageField()
    content = forms.CharField(widget=forms.Textarea)

liongram/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import ListView

from .forms import PostBaseForm
from .models import Post


def index(request):
    # post_list = Post.objects.all().select_related('writer').prefetch_related('comment_set').order_by('-created_at')
    post_list = Post.objects.all().order_by('-created_at')
    context = {
        'post_list': post_list
    }
    return render(request, 'index.html', context)


def post_list_view(request):
    return render(request, 'posts/post_list.html')


def post_detail_view(request, id):
    post = Post.objects.get(id=id)
    context = {
        'post': post
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')

        Post.objects.create(
            image=image,
            content=content,
            writer=request.user,
        )

        return redirect('index')


@login_required
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html', {'form': PostBaseForm()})
    else:
        form = PostBaseForm(request.POST, request.FILES)

        if form.is_valid():
            Post.objects.create(
                image=form.cleaned_data.get('image'),
                content=form.cleaned_data.get('content'),
                writer=request.user,
            )
        else:
            return redirect('posts:post-create')

        return redirect('index')


def post_update_view(request, id):
    post = Post.objects.get(id=id)

    if request.method == 'GET':
        context = {
            'post': post
        }
        return render(request, 'posts/post_form.html', context)
    else:
        new_image = request.FILES.get('image')
        content = request.POST.get('content')

        if new_image:
            post.image.delete()
            post.image = new_image

        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)


def post_delete_view(request, id):
    return render(request, 'posts/post_confirm_delete.html')


def url_view(request):
    print('url_view()')
    data = {'code': '001', 'msg': 'OK'}
    return HttpResponse('<h1>url_view</h1>')
    # return JsonResponse(data)


def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)


def function_view(request):
    print(f'request.method: {request.method}')

    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')


class ClassView(ListView):
    model = Post
    ordering = ['-id']
    # template_name = 'cbv_view.html'


def function_list_view(request):
    object_list = Post.objects.all().order_by('-id')
    return render(request, 'cbv_view.html', {'object_list': object_list})

liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img class="card__user-image" src="http://via.placeholder.com/32x32"/>
        <span class="card__user-name">{{ post.writer }}</span>
        {% if request.user == post.writer %}
            <a href="{% url 'posts:post-update' post.id %}">수정하기</a>
        {% endif %}
    </div>
    <div class="card__body">
        <div>
        {% if post.image %}
            <img class="card__image" src="{{ post.image.url }}">
        {% else %}
            <p>No image available</p>
        {% endif %}
    </div>
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글"/>
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기"/>
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크"/>
            </div>
        </div>
        <div class="card_content">
            <span class="card__like-num">좋아요 00개</span>
            <div class="card__main-text">
                <p><span class="card__user-name">{{ post.writer }}</span>{{ post.content |truncatechars:35 }}</p>
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">더보기</a>
                {% endif %}
            </div>
            <div>
                <p class="">댓글 {{ post.comment_set.all.count }}개 {% if not detail %}모두 보기{% endif %}</p>
                <ul class="card__comment-group">
                    {% if not detail %}
                        {% for comment in post.comment_set.all %}
                            <li><p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                            </li>
                        {% empty %}
                            <li><p>댓글 없음</p></li>
                        {% endfor %}
                    {% else %}
                        {% for comment in post.comment_set.all|slice:":2" %}
                            <li><p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                            </li>
                        {% empty %}
                            <li><p>댓글 없음</p></li>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
            <span class="card__created-at">{{ post.created_at|date:"Y년 m월 d일" }}</span>
        </div>
    </div>
</div>